Task 1

In [18]:
import numpy as np

In [19]:
rng = np.random.default_rng(seed=0)
readings = rng.normal(50,8,size=(360,4))

In [20]:
readings

array([[51.00584177, 48.94316109, 55.1233812 , 50.83920094],
       [45.71464501, 52.89276044, 60.43200036, 57.57664771],
       [44.37011811, 39.87662823, 45.0138043 , 50.33060783],
       ...,
       [44.92911842, 52.37103231, 47.93928413, 39.06261749],
       [49.79074571, 62.76561953, 66.02025854, 45.46366832],
       [57.24219683, 51.06023564, 52.27109304, 60.13896971]],
      shape=(360, 4))

In [21]:
print(readings.shape)
print(readings.dtype)
print("First Three Rows: ")
print(readings[:3])

(360, 4)
float64
First Three Rows: 
[[51.00584177 48.94316109 55.1233812  50.83920094]
 [45.71464501 52.89276044 60.43200036 57.57664771]
 [44.37011811 39.87662823 45.0138043  50.33060783]]


Task 2

In [22]:
np.random.seed(42)
readings = np.random.normal(loc=50, scale = 5, size=(360,4))

scaled_readings = (readings - readings.min()) / (readings.max() - readings.min())

centered_readings = readings - readings.mean(axis=0)

print(readings.shape)
print(scaled_readings.shape)
print(centered_readings.shape)

(360, 4)
(360, 4)
(360, 4)


Task 3

In [23]:
import numpy as np

# Re-initializing with the same seed and parameters
np.random.seed(42)
readings = np.random.normal(loc=50, scale=5, size=(360, 4))

# 1. Build a boolean mask for outliers (> 80 or < 20)
outlier_mask = (readings > 80) | (readings < 20)

# 2. Compute outlier statistics
outlier_count = np.sum(outlier_mask)
outlier_percentage = (outlier_count / readings.size) * 100

# 3. Create cleaned_readings array with NaNs
cleaned_readings = readings.copy()
cleaned_readings[outlier_mask] = np.nan

# 4. Verification
nan_count = np.count_nonzero(np.isnan(cleaned_readings))

print(f"Outlier Count: {outlier_count}")
print(f"Outlier Percentage: {outlier_percentage:.2f}%")
print(f"Number of NaNs in cleaned array: {nan_count}")
print(f"Verification Successful: {outlier_count == nan_count}")

Outlier Count: 0
Outlier Percentage: 0.00%
Number of NaNs in cleaned array: 0
Verification Successful: True


task 4

In [24]:
sensor_means = readings.mean(axis=0)
sensor_std = readings.std(axis=0)

time_means = readings.mean(axis=1)

print(sensor_means.shape)
print(sensor_std.shape)
print(time_means.shape)
print(f"Average reading for Sensor 1: {sensor_means[0]:.2f}")
print(f"Average reading at Minute 1:  {time_means[0]:.2f}")

(4,)
(4,)
(360,)
Average reading for Sensor 1: 50.15
Average reading at Minute 1:  53.16


Task 5

In [28]:
report = {
    'total_readings': readings.size,
    'outlier_count' : outlier_count,
    'outlier_percentage': outlier_percentage,
    'sensor_means' : sensor_means,
    'sensor_stds' : sensor_std
}
print(report)
#Validation check
print( report['total_readings']==readings.size)

string_report = str(report)
print(string_report)


{'total_readings': 1440, 'outlier_count': np.int64(0), 'outlier_percentage': np.float64(0.0), 'sensor_means': array([50.14616485, 50.07513934, 50.27810691, 50.29747331]), 'sensor_stds': array([4.66602003, 5.13988933, 4.93288156, 4.98570923])}
True
{'total_readings': 1440, 'outlier_count': np.int64(0), 'outlier_percentage': np.float64(0.0), 'sensor_means': array([50.14616485, 50.07513934, 50.27810691, 50.29747331]), 'sensor_stds': array([4.66602003, 5.13988933, 4.93288156, 4.98570923])}


Part 2 - Task 6

In [29]:
import numpy as np 
rng = np.random.default_rng(seed=0)
sim = rng.normal(0,1,size=(1000,6))
print(sim.shape)
print(sim.dtype)
print(sim[:3])


(1000, 6)
float64
[[ 0.12573022 -0.13210486  0.64042265  0.10490012 -0.53566937  0.36159505]
 [ 1.30400005  0.94708096 -0.70373524 -1.26542147 -0.62327446  0.04132598]
 [-2.32503077 -0.21879166 -1.24591095 -0.73226735 -0.54425898 -0.31630016]]


Task 7

In [35]:
scenario_shift = np.array([-0.3,-0.1,0.0,0.1,0.2,0.4])
adjusted_sim = scenario_shift + sim
print(adjusted_sim)
print(adjusted_sim.shape==sim.shape)

[[-0.17426978 -0.23210486  0.64042265  0.20490012 -0.33566937  0.76159505]
 [ 1.00400005  0.84708096 -0.70373524 -1.16542147 -0.42327446  0.44132598]
 [-2.62503077 -0.31879166 -1.24591095 -0.63226735 -0.34425898  0.08369984]
 ...
 [ 0.64943846  0.92922814  0.31886802  1.15773509  0.46838522  0.75055328]
 [-0.42294856  1.90252255  1.63391972 -0.39129481  1.07095129  0.64026025]
 [-0.52681171  0.64016406  0.18054669  0.25984538 -0.0263336   0.30644127]]
True


Task 8

In [39]:
scenario_means = np.mean(adjusted_sim, axis=0)

scenario_ranks = np.argsort(scenario_means)
partitioned_means = np.partition(scenario_means, -2)
top_two_partitioned = partitioned_means[-2:]

full_sort_top_two = np.sort(scenario_means)[-2:]
print(np.array_equal(np.sort(top_two_partitioned), full_sort_top_two))

True


Task 9

In [44]:
rng = np.random.default_rng(seed=0)
sim_2 = rng.normal(0,1,size=(1000,6))
print(sim==sim_2)
rng_3 = np.random.default_rng(seed=2)
sim_3 = rng.normal(0,1,size=(1000,6))
print(sim_3!=sim)

match_1_2 = np.array_equal(sim, sim_2)
match_1_3 = np.array_equal(sim, sim_3)
print(match_1_2, match_1_3)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 ...
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 ...
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
True False


Task 10

In [ ]:
report = {
    'shape' : sim.shape,
    'scenario_means' : scenario_means,
    'top_two_indices' : scenario_ranks[-2:],
    'top_two_value' : top_two_partitioned
    }

print(len(scenario_means)==6)
print(len(top_two_indices)==2)

True
